# Generated by Django 4.2.16 on 2026-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
